language: python

python:
  - "2.7"
#  - "3.5"

install:
  - pip install -r requirements.txt
  - cd docs && sphinx-build -b html -w build.log -d _build/doctrees . _build/html
  
script:
  - nosetests --with-xunit --xunit-file=nosetests.xml

cache: pip
